name: Generate Checksums

on:
  push:
    branches:
      - master

jobs:
  generate-checksums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate checksums
        run: |
          find . -type f -exec sha256sum {} + > checksums.txt
      - name: Display checksums
        run: cat checksums.txt
